# Generated by Django 4.2.23 on 2025-06-11 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Name of the student', max_length=255)),
                ('original_text', models.TextField(help_text='The text the student was asked to read.')),
                ('audio_file', models.FileField(help_text="Uploaded audio recording of the student's reading.", upload_to='student_audio/')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('evaluation_status', models.CharField(default='Pending', help_text='Status of the pronunciation evaluation (e.g., Pending, Processing, Completed, Failed).', max_length=50)),
                ('feedback_json', models.JSONField(blank=True, help_text='JSON field to store detailed pronunciation feedback.', null=True)),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
